"use strict";
$().ready(function(){
    price_form_zz_call();
    modal_zz_call();
    catalog_zz_call();
    swipe_slider_zz_call();
    start_zz_call();
    paly_video_zz_call();
    personal_area_zz_call();
    menu_zz_call();
    login_zz_call();
    cart_zz_call();
    time_counter_zz_call();
    loader_zz_call();
    zz_scroll_modal();
    zz_auth_modal();
    delivery_tab();
    mask_zz_call();
});